[build-system]
requires = ["hatchling==1.27.0"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build]
include = ["vhap/**/*.py"]

[project]
name = "VHAP"
version = "0.1.0"
requires-python = ">=3.11,<3.12"
dependencies = [
    "tyro==0.8.14",
    "pyyaml==6.0.3",
    "numpy==2.2.6",
    "matplotlib==3.10.7",
    "scipy==1.16.3",
    "pillow==12.0.0",
    "opencv-python==4.12.0.88",
    "ffmpeg-python==0.2.0",
    "colour-science==0.4.6",
    "torch==2.9.1",  # install from the CUDA 12.8 PyTorch index
    "torchvision==0.24.1",  # install from the CUDA 12.8 PyTorch index
    "protobuf==4.25.5",
    "tensorboard==2.20.0",
    "chumpy@git+https://github.com/mattloper/chumpy.git@580566eafc9ac68b2614b64d6f7aaa84eebb70da",
    "trimesh==4.8.3",
    "nvdiffrast@git+https://github.com/MTamon/nvdiffrast@cuda128-backface-culling",
    "BackgroundMattingV2@git+https://github.com/MTamon/BackgroundMattingV2@cuda128",
    "STAR@git+https://github.com/MTamon/STAR@cuda128",
    "dlib==19.24.6",  # for STAR
    "python-gflags==3.1.2",  # for STAR
    "imgaug==0.4.0",  # for STAR
    "lmdb==1.7.5",  # for STAR
    "lxml==6.0.2",  # for STAR
    "imageio==2.37.2",  # for STAR/imgaug
    "shapely==2.1.2",  # for imgaug
    "tqdm==4.67.1",
    "pandas==2.3.3",  # for STAR
    "gdown==5.2.0",  # for STAR
    "face-alignment==1.4.1",
    "dearpygui==1.11.1",
    "joblib==1.5.2"
]
authors = [
  {name = "Shenhan Qian", email = "shenhan.qian@tum.de"},
]

description = "A complete head tracking pipeline from videos to NeRF-ready datasets."
readme = "README.md"
